# Generated by Django 5.1.7 on 2025-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="menu_item_description",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
